services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    networks:
      - amar
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: amar
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - amar

  nginx:
    image: nginx:latest
    container_name: server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - amar

volumes:
  db_data:

networks:
  amar:
    driver: bridge
